const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const skills = [
    {
        name: 'math-writing',
        description: 'Write, redesign, revise, or audit rigorous mathematical prose while making intended changes to assumptions, quantifiers, scope, and conclusions explicit. Use for definitions, statements, proofs, counterexamples, notation, boundary cases, conceptual rewrites, and mathematical necessity review in any project.',
        artifact: 'skills/math-writing.md',
        source: 'skills-src/math-writing.vasm.md'
    },
    {
        name: 'lean-formalization',
        description: 'Anchor, implement, review, or reorganize Lean 4 formalizations for a project prepared with Math Workspace. Use when Lean declarations must correspond to stable Markdown formal objects, when checking anchor coverage, or when validating Lean/source alignment without overstating proof coverage.',
        artifact: 'skills/lean-formalization.md',
        source: 'skills-src/lean-formalization.vasm.md'
    }
];

for (const skill of skills) {
    const artifactPath = path.join(root, skill.artifact);
    const targetPath = path.join(root, 'plugins', 'math-workspace', 'skills', skill.name, 'SKILL.md');
    const body = fs.readFileSync(artifactPath, 'utf8').trim();
    if (!body.startsWith('# ')) {
        throw new Error(`${skill.artifact} must start with a level-one heading`);
    }
    const output = [
        '---',
        `name: ${skill.name}`,
        `description: ${skill.description}`,
        '---',
        '',
        `<!-- Generated from ${skill.source}; do not edit this file directly. -->`,
        '',
        body,
        ''
    ].join('\n');
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.writeFileSync(targetPath, output, 'utf8');
}
